### ISSUE TITLE
json_query

### ISSUE THREAD

**Issue by peppicus** [jadsonbr/pyreport#9]
Hi, when i try to use json file, i receive this error:

jasperstarter: error: argument --json-query: expected one argument
Traceback (most recent call last):
  File "jreport.py", line 97, in <module>
    processingJson('testJson.jrxml')
  File "jreport.py", line 31, in processingJson
    locale='en_US'
  File "/usr/local/lib/python2.7/dist-packages/pyjasper/jasperpy.py", line 144, in process
    return self.execute()
  File "/usr/local/lib/python2.7/dist-packages/pyjasper/jasperpy.py", line 183, in execute
    output = subprocess.check_call(self.command, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/lib/python2.7/dist-packages/pyjasper/jasperstarter/bin/jasperstarter --locale en_US process "/home/gtraficante/JaspersoftWorkspace/MyReports/testJson.jrxml" -o "/home/gtraficante/JaspersoftWorkspace/MyReports/output" -f pdf rtf -t json --data-file /home/gtraficante/Dropbox/python/report/first.json --json-query ' returned non-zero exit status 1

Probably it depend form parameter json_query, i don't know how it should be setted.

```
    jasper.process(
         input_file,
         output_file=output,
         format_list=["pdf", "rtf"],
         db_connection={
            'data_file': data_file,
            'driver': 'json',
            'json_query': '',
         },
         locale='en_US'
    )

```

**Comment by peppicus** [comment]
ok, i understood.

tnks anyway
